name: Deploy

on:
  push:
    branches:
      - api
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
              sentryProjectId
              sentryKey
              toEmail
              captchaVerifyUrl
              captchaSecret
              captchaSiteKey
              sendgridUrl
              sendgridKey
        env:
          sentryProjectId: ${{ secrets.SENTRYPROJECTID }}
          sentryKey: ${{ secrets.SENTRYKEY }}
          toEmail: ${{ secrets.TOEMAIL }}
          captchaSecret: ${{ secrets.captchaSecret }}
          captchaSiteKey: ${{ secrets.captchaSiteKey }}
          sendgridUrl: ${{ secrets.sendgridUrl }}
          sendgridKey: ${{ secrets.sendgridKey }}